# Interpolação única: Vetorial (MVTools, estilo SVP)
# Ctrl+G -> liga [interp-vector]
# Ctrl+Shift+I -> desliga interpolação
ctrl+g       apply-profile interp-vector; show-text "Interpolação ON (Vetorial/MVTools adaptativo)"
ctrl+I       change-list vf clr ""; set video-sync audio; set hwdec auto-safe; set display-fps-override 0; show-text "Interpolação OFF"
