# ######## Window rules — General ########

# Uncomment to apply global transparency to all windows:
# windowrulev2 = opacity 0.89 override 0.89 override, class:.*

# Disable blur for xwayland context menus
windowrule = no_blur on, match:class ^()$, match:title ^()$
# windowrulev2 = noblur, xwayland:1
windowrule = no_blur on, match:fullscreen 1
windowrule = opacity 1.0 1.0, match:fullscreen 1
# windowrule = opacity 0.90 0.90, match:class ^(google-chrome)$
# windowrulev2 = opacity 0.80 0.80,class:^(firefox)$
windowrule = opacity 0.90 0.90, match:class ^(org.telegram.desktop)$
windowrule = opacity 0.90 0.90, match:class ^(thunar)$
windowrule = opacity 0.90 0.90, match:class ^(code)$
windowrule = opacity 0.90 0.90, match:class ^(code-oss)$
windowrule = opacity 0.90 0.90, match:class ^(code-url-handler)$
windowrule = opacity 0.90 0.90, match:class ^(code-insiders-url-handler)$
windowrule = opacity 0.90 0.90, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = opacity 0.90 0.90, match:class ^(qt5ct)$
windowrule = opacity 0.90 0.90, match:class ^(qt6ct)$
windowrule = opacity 0.90 0.90, match:class ^(org.kde.ark)$
windowrule = opacity 0.90 0.90, match:class ^(com.obsproject.Studio)$
windowrule = opacity 0.90 0.90, match:class ^(Alacritty)$
windowrule = opacity 0.90 0.90, match:class ^(kitty)$
windowrule = opacity 0.90 0.90, match:class ^(blueman-manager)$
windowrule = opacity 0.90 0.90, match:class ^([Ss]team)$
windowrule = opacity 0.90 0.90, match:class ^(steamwebhelper)$
windowrule = opacity 0.90 0.90, match:class ^(dev\.vencord\.Vesktop|vesktop)$
windowrule = opacity 0.90 0.90, match:class ^(WebCord)$
windowrule = opacity 0.90 0.90, match:class ^(yad)$
windowrule = opacity 0.90 0.90, match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = opacity 0.90 0.90, match:class ^(polkit-gnome-authentication-agent-1)$
windowrule = opacity 0.90 0.90, match:class ^(org.freedesktop.impl.portal.desktop.gtk)$
windowrule = opacity 0.90 0.90, match:class ^(org.freedesktop.impl.portal.desktop.hyprland)$
windowrule = opacity 0.90 0.90, match:class ^(org.gnome.Loupe)$
windowrule = opacity 0.90 0.90, match:class ^(org.gnome.Calculator)$
windowrule = opacity 0.90 0.90, match:class ^(io.missioncenter.MissionCenter)$
windowrule = opacity 0.90 0.90, match:class ^(evince)$
