# ######## Layer rules ########

layerrule = xray 1, match:namespace .*
# layerrule = noanim, .*
layerrule = no_anim on, match:namespace walker
layerrule = no_anim on, match:namespace selection
layerrule = no_anim on, match:namespace overview
layerrule = no_anim on, match:namespace anyrun
layerrule = no_anim on, match:namespace indicator.*
layerrule = no_anim on, match:namespace osk
layerrule = no_anim on, match:namespace hyprpicker

layerrule = blur on, match:namespace gtk-layer-shell
layerrule = ignore_alpha 0, match:namespace gtk-layer-shell
layerrule = blur on, match:namespace launcher
layerrule = ignore_alpha 0.5, match:namespace launcher
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0.69, match:namespace notifications
layerrule = blur on, match:namespace logout_dialog # wlogout

# ags
layerrule = animation slide left, match:namespace sideleft.*
layerrule = animation slide right, match:namespace sideright.*
layerrule = blur on, match:namespace session[0-9]*
layerrule = blur on, match:namespace bar[0-9]*
layerrule = ignore_alpha 0.6, match:namespace bar[0-9]*
layerrule = blur on, match:namespace barcorner.*
layerrule = ignore_alpha 0.6, match:namespace barcorner.*
layerrule = blur on, match:namespace dock[0-9]*
layerrule = ignore_alpha 0.6, match:namespace dock[0-9]*
layerrule = blur on, match:namespace indicator.*
layerrule = ignore_alpha 0.6, match:namespace indicator.*
layerrule = blur on, match:namespace overview[0-9]*
layerrule = ignore_alpha 0.6, match:namespace overview[0-9]*
layerrule = blur on, match:namespace cheatsheet[0-9]*
layerrule = ignore_alpha 0.6, match:namespace cheatsheet[0-9]*
layerrule = blur on, match:namespace sideright[0-9]*
layerrule = ignore_alpha 0.6, match:namespace sideright[0-9]*
layerrule = blur on, match:namespace sideleft[0-9]*
layerrule = ignore_alpha 0.6, match:namespace sideleft[0-9]*
layerrule = blur on, match:namespace indicator.*
layerrule = ignore_alpha 0.6, match:namespace indicator.*
layerrule = blur on, match:namespace osk[0-9]*
layerrule = ignore_alpha 0.6, match:namespace osk[0-9]*

layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0, match:namespace rofi
