# ######## Workspace rules — Workspace 6 (Media) ########

# Workspace display settings: no rounding, gaps or borders
workspace = 6, rounding:false, gapsin:0, gapsout:0, border:false

# Stremio → workspace 6
windowrulev2 = workspace 6 silent, class:^(com.stremio.stremio)$

# MPV
windowrulev2 = immediate, class:^(mpv)$
windowrulev2 = idleinhibit focus, class:^(mpv)$
