# ######## Workspace rules — Workspace 4 (Social) ########

# Force Spotify, Steam web helper and Steam to workspace 4 silently
windowrule = workspace 4 silent, match:class ^(spotify)$
windowrule = workspace 4 silent, match:class ^(steamwebhelper)$
windowrule = workspace 4 silent, match:class ^([Ss]team)$
windowrule = float on, match:class ^(steam)$, match:title negative:^(Steam)$