# ######## Workspace rules — Workspace 8 (Auxiliar) ########

# Aplicações que abrem silenciosamente no auxiliar
windowrule = workspace 8 silent, match:class ^(com.discordapp.Discord)$
windowrule = workspace 8 silent, match:class ^(vesktop)$