# ######## Workspace rules — Special workspaces ########

workspace = special:special, gapsout:30

# Regras globais para o workspace de rascunho (stash)
windowrule = center on, match:workspace special:stash
windowrule = pin on, match:workspace special:stash
windowrule = float on, match:workspace special:stash

windowrule = workspace special:stash silent, match:class ^(spotify)$
windowrule = size 40% 50%, match:class ^(spotify)$
windowrule = move 58% 5%, match:class ^(spotify)$

windowrule = workspace special:stash silent, match:class ^(SVPManager)$
windowrule = size 30% 40%, match:class ^(SVPManager)$

windowrule = workspace special:stash silent, match:class ^([Ss]team)$
windowrule = float on, match:class ^(steam)$, match:title negative:^(Steam)$

# Fix para a janela flutuante do "xwaylandvideobridge"
# windowrulev2 = workspace special:stash2 silent, class:^(xwaylandvideobridge)$, title:^(Wayland para ponte de gravação X — Ponte de vídeo Xwayland)$
