# ######## Workspace rules — Workspace 4 (Social) ########

# Force Discord and Steam web helper to workspace 4 silently
windowrule = workspace 4 silent, match:class ^(com.discordapp.Discord)$
windowrule = workspace 4 silent, match:class ^(steamwebhelper)$
windowrule = workspace 4 silent, match:class ^(vesktop)$