# ######## Workspace rules — Workspace 5 (Gaming) ########

# Workspace display settings: no rounding, gaps or borders
workspace = 5, rounding:false, gapsin:0, gapsout:0, border:false

layerrule = noanim,5
layerrule = ignorezero,5

# Force all Steam games to workspace 5 silently
windowrulev2 = workspace 5 silent, class:^dota2*$
windowrulev2 = workspace 5 silent, class:^Albion.*$
windowrulev2 = workspace 5 silent, class:^steam_app_.*$
windowrulev2 = workspace 5 silent, class:^(Albion-Online)$, title:^(Albion Online Client)$
windowrulev2 = workspace 5 silent, class:^(osu!)$, title:^(osu!)$

# Performance rules for osu! (seguindo o seu padrão de games)
windowrulev2 = float, class:^(osu!)$
windowrulev2 = fullscreen, class:^(osu!)$
windowrulev2 = opaque, class:^(osu!)$
windowrulev2 = noborder, class:^(osu!)$
windowrulev2 = noshadow, class:^(osu!)$
windowrulev2 = noanim, class:^(osu!)$

# Make Steam games float
windowrulev2 = float, class:^steam_app_.*$
windowrulev2 = float, class:^dota2*$

# Force fullscreen
windowrulev2 = fullscreen, class:^steam_app_.*$
# windowrulev2 = fullscreenstate:fullscreen, class:^steam_app_.*$
windowrulev2 = fullscreen, class:^dota2*$
# windowrulev2 = fullscreenstate:fullscreen, class:^dota2*$

# Direct scanout-friendly rules (removes extra effects)
windowrulev2 = opaque, class:^steam_app_.*$
windowrulev2 = noborder, class:^steam_app_.*$
windowrulev2 = noshadow, class:^steam_app_.*$
windowrulev2 = noanim, class:^steam_app_.*$
windowrulev2 = opaque, class:^dota2*$
windowrulev2 = noborder, class:^dota2*$
windowrulev2 = noshadow, class:^dota2*$
windowrulev2 = noanim, class:^dota2*$
# windowrulev2 = immediate, class:^steam_app_.*$

# Set content type to "game" (may help with special behavior or direct scanout)
# windowrulev2 = contenttype:game, class:^steam_app_.*$
# windowrulev2 = contenttype:game, class:^dota2*$

# Regra específica para o Gamescope
windowrulev2 = immediate, class:^(gamescope)$
windowrulev2 = fullscreen, class:^(gamescope)$
windowrulev2 = monitor 0, class:^(gamescope)$
windowrulev2 = workspace 5 silent, class:^(gamescope)$

# Opcional: remover blur/gaps quando o gamescope estiver aberto para garantir performance
windowrulev2 = noblur, class:^(gamescope)$
windowrulev2 = nodim, class:^(gamescope)$
