# ######## Workspace rules — Workspace 8 (Auxiliar) ########

# Aplicações que abrem silenciosamente no auxiliar
windowrule = workspace 8 silent, match:class ^(spotify)$
windowrule = workspace 8 silent, match:class ^(SVPManager)$
windowrule = workspace 8 silent, match:class ^(steamwebhelper)$
windowrule = workspace 8 silent, match:class ^([Ss]team)$
windowrule = float on, match:class ^(steam)$, match:title negative:^(Steam)$
