# ######## Workspace rules — Workspace 6 (Media) ########

# Workspace display settings: no rounding, gaps or borders
workspace = 6, rounding:false, gapsin:0, gapsout:0, border:false

# Stremio → workspace 6
windowrule = workspace 6 silent, match:class ^(com.stremio.stremio)$

# MPV
windowrule = workspace 6 silent, match:class ^(mpv)$
windowrule = immediate on, match:class ^(mpv)$
windowrule = idle_inhibit focus, match:class ^(mpv)$
