# ######## Workspace rules — Workspace 7 (Stash) ########

# Aplicações que abrem silenciosamente no stash
windowrule = workspace 7 silent, match:class ^(spotify)$
windowrule = workspace 7 silent, match:class ^(SVPManager)$
windowrule = workspace 7 silent, match:class ^([Ss]team)$
windowrule = float on, match:class ^(steam)$, match:title negative:^(Steam)$
