# ######## Workspace rules — Special workspaces ########

workspace = special:special, gapsout:30

# Regras globais para o workspace de rascunho (stash)
windowrulev2 = center, workspace:special:stash
windowrulev2 = pin, workspace:special:stash
windowrulev2 = float, workspace:special:stash

windowrulev2 = workspace special:stash silent, class:^(Spotify)$
windowrulev2 = size 40% 50%, class:^(Spotify)$
windowrulev2 = move 58% 5%, class:^(Spotify)$

windowrulev2 = workspace special:stash silent, class:^(SVPManager)$
windowrulev2 = size 30% 40%, class:^(SVPManager)$

windowrulev2 = workspace special:stash silent, class:^([Ss]team)$
windowrule = float, class:^(steam)$, title:negative:^(Steam)$

# Fix para a janela flutuante do "xwaylandvideobridge"
# windowrulev2 = workspace special:stash2 silent, class:^(xwaylandvideobridge)$, title:^(Wayland para ponte de gravação X — Ponte de vídeo Xwayland)$
