# ######## Window rules — Hub ########
# Each file groups rules by workspace or function.

source = ~/.config/hypr/hyprland/windowrules/general.conf
source = ~/.config/hypr/hyprland/windowrules/floating.conf
source = ~/.config/hypr/hyprland/windowrules/layerrules.conf
source = ~/.config/hypr/hyprland/windowrules/workspace-special.conf
source = ~/.config/hypr/hyprland/windowrules/workspace-4-social.conf
source = ~/.config/hypr/hyprland/windowrules/workspace-5-gaming.conf
source = ~/.config/hypr/hyprland/windowrules/workspace-6-media.conf
